---
- block:
  - block:
    - name: install git completion
      get_url:
        url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
        dest: "{{ gitconfig_completion_path }}"
        mode: 0755
    when: xfacts.distro.osfamily == 'redhat'
    become: true

  - name: create prompt config for git
    template: src=git_bashrc_prompt dest="{{ gitconfig_bashrc_prompt_path }}" mode=0700

  - name: include prompt config to bashrc
    lineinfile:
      dest: "{{ bash_bashrc_path }}"
      create: yes
      line: ". {{ gitconfig_bashrc_prompt_path }}"
  when: gitconfig_prompt|bool
