---
- name: override defaults
  set_fact:
    _bash:
      prompt: "{{ bash.prompt | default(_bash_defaults.prompt) }}"
      bashrc_path: "{{ _bash.bashrc_path }}"
      prompt_conf_path: "{{ _bash.prompt_conf_path }}"

- name: create bashrc file
  file: path="{{ _bash.bashrc_path }}" state=file mode=0644

- include_tasks: manage-completion.yml
- include_tasks: manage-prompt.yml
