---
- block:
  - name: copy custom bashrc prompt config
    copy: src=bashrc_prompt dest="{{ bash_prompt_conf_path }}" mode=0600

  - name: include custom bashrc prompt config to bashrc
    lineinfile:
      dest: "{{ bash_bashrc_path }}"
      line: ". {{ bash_prompt_conf_path }}"
      state: present
  when: bash_change_prompt|bool

- block:
  - name: delete custom bashrc prompt config
    file: path="{{ bash_prompt_conf_path }}" state=absent

  - name: exclude custom bashrc prompt config from bashrc
    lineinfile:
      dest: "{{ bash_bashrc_path }}"
      line: ". {{ bash_prompt_conf_path }}"
      state: absent
  when: not bash_change_prompt
