---
- name: install bash completion
  package: name=bash-completion state=present
  become: true

- name: configure bash completion
  lineinfile:
    dest: "{{ _bash.bashrc_path }}"
    line: ". /usr/share/bash-completion/bash_completion"
    state: present
