---
- fail: msg="samba_shares.shares.name is required"
  when: samba_shares_share.name is undefined

- fail: msg="samba_shares.shares.dir is required"
  when: samba_shares_share.dir is undefined

- fail: msg="samba_shares.shares.user is required"
  when: samba_shares_share.user is undefined

- fail: msg="samba_shares.shares.group is required"
  when: samba_shares_share.group is undefined

- block:
  - name: create samba custom configuration for {{ samba_shares_share.name }}
    template:
      src: my-smbd.conf.j2
      dest: "{{ samba_shares_share_conf_file }}"
      owner: root
      group: root
      mode: 0644

  - name: configure samba
    lineinfile:
      dest: /etc/samba/smb.conf
      line: "include = {{ samba_shares_share_conf_file }}"
    notify: restart samba

  - name: create share directory {{ samba_shares_share.dir }}
    file:
      path: "{{ samba_shares_share.dir }}"
      owner: "{{ samba_shares_share.user }}"
      group: "{{ samba_shares_share.group }}"
      mode: "{{ samba_shares_share.dir_mode }}"
      state: directory
  become: true
